version: "3"

tasks:
  protogen:
    desc: Generate protobuf code for the example
    cmds:
      - >
        protoc -I ./example/api
        --go_out=./example/protogen --go_opt=paths=source_relative --go-grpc_out=./example/protogen
        --grpc-gateway_out ./example/protogen --grpc-gateway_opt=paths=source_relative
        --go-grpc_opt=paths=source_relative
        example/api/greeter.proto

  run-server:
    desc: Run the gRPC server
    cmds:
      - go run example/server/cmd/main.go

  run-grpc-client:
    desc: Run the gRPC client
    cmds:
      - go run example/client/grpc/main.go

  run-http-client:
    desc: Run the HTTP client
    cmds:
      - go run example/client/http/main.go
